# Generated by Django 3.1.4 on 2021-01-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('reg_event', models.CharField(max_length=255)),
                ('reg_type', models.CharField(max_length=255)),
                ('nop', models.PositiveIntegerField()),
            ],
        ),
    ]
