# Generated by Django 3.1.4 on 2021-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreg',
            name='event_poster',
            field=models.ImageField(upload_to='eventPoster'),
        ),
    ]
