# Generated by Django 3.1.4 on 2021-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210123_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreg',
            name='event_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventreg',
            name='event_endate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventreg',
            name='event_stdate',
            field=models.DateTimeField(),
        ),
    ]
